### ISSUE TITLE
一部の動画で720pまでしか再生できない

### ISSUE THREAD

**Issue by hokkaman** [logore/amazon-prime-video-1080p#10]
映画「グランツーリスモ」で1080pで再生することができません。
おま環なのか分かりませんが調べてもらうことできますか？
ちなみにChrome、Edge両方とも720pでした。

https://www.amazon.co.jp/%E3%82%B0%E3%83%A9%E3%83%B3%E3%83%84%E3%83%BC%E3%83%AA%E3%82%B9%E3%83%A2-%E3%83%87%E3%83%B4%E3%82%A3%E3%83%83%E3%83%89%E3%83%BB%E3%83%8F%E3%83%BC%E3%83%90%E3%83%BC/dp/B0CHND2G43/

**Comment by vud0** [comment]
issueありがとうございます。

@logore の別アカウントです

Windows、macOSで確認してみたところ、その作品は元々720pでしか配信されていないと思います。

**Comment by vud0** [comment]
@hokkaman 

issueありがとうございます。

@logore の別アカウントです

Windows、macOSで確認してみたところ、その作品は元々720pでしか配信されていないと思います。

**Comment by hokkaman** [comment]
ご確認ありがとうございました。
720pでしか配信されていないのであればどうしようもなさそうですね。

作品ページにはUHD表示がありますがブラウザ視聴では制限がかかってるってことなんですかね？

**Comment by vud0** [comment]
@hokkaman 

過去のissueでもほかのユーザーと議論していましたが、ブラウザでは現在の仕様上では、FHD(1080p) が限界だと思います。
以下、参考になると思われるリファレンスです。

https://dobonkai.hatenablog.com/entry/Primevideo

**Comment by hokkaman** [comment]
参考URLありがとうございます。
あくまで作品ページのUHD表示は「Amazonデバイスor4Kテレビで視聴したとき」ってことですね。
なんともモヤモヤする表記の仕方ですねぇ・・・

せめてブラウザ視聴でも1080p配信は完備されてほしいものです。
